import React, { useState } from 'react';
import MpesaForm from './MpesaForm';
import ScreenshotUpload from './ScreenshotUpload';
import WhatsAppButton from '../whatsapp/WhatsAppButton';
import { useAuth } from '../../context/AuthContext';
import { useSettings } from '../../context/SettingsContext';
import { initiateSTKPush, initiateManualPayment, uploadScreenshot } from '../../services/paymentService';
import { formatKES } from '../../utils/formatters';

const PaymentModal = ({ item, onClose, onSuccess }) => {
  const [method, setMethod] = useState('');
  const [loading, setLoading] = useState(false);
  const [transactionId, setTransactionId] = useState(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const { user } = useAuth();
  const { settings, formatPaymentInstructions } = useSettings();

  const businessNumber = settings?.businessPhoneNumber || '0768784909';

  const handleSTKPush = async (phone) => {
    if (!settings?.enableSTKPush) {
      alert('STK Push is currently disabled. Please use manual payment.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const data = await initiateSTKPush(item._id, item.type, phone);
      setTransactionId(data.transactionId);
      setMethod('autogenerated');
    } catch (error) {
      console.error('STK Push error:', error);
      const msg = error.response?.data?.message || 'Payment failed. Please try again.';
      if (msg.includes('already own')) {
        alert('You already own this item. No payment needed.');
        onClose();
      } else {
        setError(msg);
        alert(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleManualPayment = async () => {
    if (!settings?.enableManualPayment) {
      alert('Manual payment is currently disabled. Please use STK Push.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const data = await initiateManualPayment(item._id, item.type);
      setTransactionId(data.transactionId);
      setMethod('manual');
    } catch (error) {
      console.error('Manual payment error:', error);
      const msg = error.response?.data?.message || 'Failed to initiate manual payment';
      if (msg.includes('already own')) {
        alert('You already own this item. No payment needed.');
        onClose();
      } else {
        setError(msg);
        alert(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleScreenshotUpload = async (file) => {
    setLoading(true);
    setError('');
    try {
      await uploadScreenshot(transactionId, file);
      alert('✅ Screenshot uploaded! Awaiting verification.');
      if (onSuccess) onSuccess();
      setTimeout(() => onClose(), 2000);
    } catch (error) {
      console.error('Screenshot upload error:', error);
      const msg = error.response?.data?.message || 'Upload failed';
      setError(msg);
      alert(`❌ ${msg}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h3>Complete Payment</h3>
          <button className="modal-close" onClick={onClose}>×</button>
        </div>
        <div className="modal-body">
          {/* Item Details */}
          <div style={{ textAlign: 'center', marginBottom: '24px', padding: '16px', backgroundColor: '#f8fafc', borderRadius: '8px' }}>
            <h4 style={{ fontSize: '18px', color: '#2d3748', marginBottom: '4px' }}>{item.title}</h4>
            <div style={{ fontSize: '14px', color: '#718096', marginBottom: '8px' }}>{item.type === 'software' ? '💻 Software' : '📄 Document'}</div>
            <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#667eea' }}>{formatKES(item.price)}</div>
          </div>

          {error && (
            <div style={{ backgroundColor: '#fed7d7', color: '#c53030', padding: '12px', borderRadius: '8px', marginBottom: '20px', textAlign: 'center' }}>
              ❌ {error}
            </div>
          )}

          {/* Payment Method Selection */}
          {!method && !transactionId && (
            <>
              <div style={{ display: 'flex', gap: '16px', marginBottom: '24px', flexWrap: 'wrap' }}>
                {settings?.enableSTKPush && (
                  <button
                    style={{ flex: '1 1 200px', padding: '20px', border: '2px solid #e2e8f0', borderRadius: '12px', backgroundColor: '#fff', cursor: 'pointer', transition: 'all 0.3s', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '8px' }}
                    onClick={() => setMethod('autogenerated')}
                    disabled={loading}
                  >
                    <span style={{ fontSize: '32px' }}>📱</span>
                    <span style={{ fontSize: '16px', fontWeight: '600', color: '#2d3748' }}>STK Push</span>
                    <span style={{ fontSize: '12px', color: '#718096' }}>Instant payment via M-Pesa</span>
                  </button>
                )}
                {settings?.enableManualPayment && (
                  <button
                    style={{ flex: '1 1 200px', padding: '20px', border: '2px solid #e2e8f0', borderRadius: '12px', backgroundColor: '#fff', cursor: 'pointer', transition: 'all 0.3s', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '8px' }}
                    onClick={handleManualPayment}
                    disabled={loading}
                  >
                    <span style={{ fontSize: '32px' }}>💰</span>
                    <span style={{ fontSize: '16px', fontWeight: '600', color: '#2d3748' }}>Send to Owner</span>
                    <span style={{ fontSize: '12px', color: '#718096' }}>Manual verification required</span>
                  </button>
                )}
              </div>

              {method === 'autogenerated' && (
                <MpesaForm onSubmit={handleSTKPush} loading={loading} />
              )}
            </>
          )}

          {/* STK Push Waiting Screen */}
          {method === 'autogenerated' && transactionId && (
            <div style={{ textAlign: 'center', padding: '20px' }}>
              <div style={{ fontSize: '48px', marginBottom: '16px' }}>📱</div>
              <h3 style={{ fontSize: '20px', color: '#2d3748', marginBottom: '12px' }}>STK Push Sent!</h3>
              <p style={{ color: '#718096', marginBottom: '20px', lineHeight: '1.6' }}>
                Please check your phone and enter your M-Pesa PIN to complete the payment.
              </p>
              <div className="spinner" style={{ margin: '0 auto' }}></div>
              <p style={{ color: '#a0aec0', fontSize: '14px', marginTop: '12px', marginBottom: '20px' }}>
                Waiting for payment confirmation...
              </p>
              <WhatsAppButton
                message={`Hello, I'm trying to pay ${formatKES(item.price)} for ${item.title} via STK Push but not receiving the prompt.`}
              />
            </div>
          )}

          {/* Manual Payment Screen */}
          {method === 'manual' && transactionId && (
            <>
              <div style={{ backgroundColor: '#ebf8ff', padding: '16px', borderRadius: '8px', marginBottom: '20px' }}>
                <h4 style={{ color: '#2c5282', marginBottom: '8px' }}>📋 Payment Instructions:</h4>
                <p style={{ color: '#2d3748', marginBottom: '12px', fontSize: '14px' }}>{formatPaymentInstructions(settings?.paymentInstructions)}</p>
              </div>

              <div style={{ marginTop: '8px' }}>
                <h4 style={{ fontSize: '18px', fontWeight: '600', color: '#2d3748', marginBottom: '16px', textAlign: 'center' }}>💵 Send Money to Owner</h4>
                
                <div style={{ backgroundColor: '#f7fafc', borderRadius: '12px', padding: '16px', marginBottom: '20px', border: '1px solid #e2e8f0' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 0', borderBottom: '1px solid #e2e8f0' }}>
                    <span style={{ fontSize: '24px', width: '40px' }}>🏦</span>
                    <div>
                      <strong>Paybill Number:</strong> {businessNumber}
                      <button onClick={() => copyToClipboard(businessNumber)} style={{ marginLeft: '8px', padding: '2px 6px', backgroundColor: '#e2e8f0', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '12px' }}>{copied ? '✓' : '📋'}</button>
                    </div>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 0', borderBottom: '1px solid #e2e8f0' }}>
                    <span style={{ fontSize: '24px', width: '40px' }}>🛒</span>
                    <div>
                      <strong>Account Number:</strong> <span style={{ fontFamily: 'monospace', fontWeight: '600', color: '#667eea' }}>DocuSoft</span>
                      <button onClick={() => copyToClipboard('DocuSoft')} style={{ marginLeft: '8px', padding: '2px 6px', backgroundColor: '#e2e8f0', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '12px' }}>{copied ? '✓' : '📋'}</button>
                    </div>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 0' }}>
                    <span style={{ fontSize: '24px', width: '40px' }}>💰</span>
                    <div>
                      <strong>Amount:</strong> <span style={{ fontWeight: '700', color: '#48bb78', fontSize: '18px' }}>{formatKES(item.price)}</span>
                    </div>
                  </div>
                </div>

                <div style={{ backgroundColor: '#fff9e6', borderRadius: '12px', padding: '16px', marginBottom: '20px', border: '1px solid #fef3c7' }}>
                  <p style={{ fontWeight: '600', color: '#b45309', marginBottom: '12px' }}>📱 How to Send Money via M-Pesa:</p>
                  <ol style={{ marginLeft: '20px', fontSize: '13px', color: '#4a5568', lineHeight: '1.8' }}>
                    <li>Go to <strong>Safaricom M-Pesa</strong> on your phone</li>
                    <li>Select <strong>Send Money</strong></li>
   {/*                 <li>Select <strong>Pay Bill</strong> (for Paybill) or <strong>Buy Goods & Services</strong> (for Till)</li>    */}
                    <li>Enter Number: <strong>{businessNumber}</strong></li>
      {/*              <li>Enter Account Number / Till: <strong>DocuSoft</strong></li>            */}
                    <li>Enter Amount: <strong>{formatKES(item.price)}</strong></li>
                    <li>Enter your M-Pesa PIN and confirm</li>
                    <li>Wait for confirmation SMS from M-Pesa</li>
                    <li>Take a <strong>screenshot</strong> of the confirmation</li>
                    <li>Upload the screenshot below</li>
                  </ol>
                </div>

                <ScreenshotUpload onUpload={handleScreenshotUpload} loading={loading} />

                <div style={{ marginTop: '20px', textAlign: 'center' }}>
                  <p style={{ color: '#718096', fontSize: '13px', marginBottom: '8px' }}>After sending money, notify the owner:</p>
                  <WhatsAppButton
                    message={`Hello, I just sent ${formatKES(item.price)} for ${item.title} via M-Pesa. Please verify. Transaction ID: ${transactionId}`}
                  />
                </div>

                <div style={{ marginTop: '16px', padding: '12px', backgroundColor: '#feebc8', borderRadius: '8px', textAlign: 'center', fontSize: '12px', color: '#7b341e' }}>
                  <p>⏳ Your payment will be verified by the admin within 24 hours.</p>
                  <p>You will receive a confirmation once approved.</p>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default PaymentModal;