import React, { useState } from 'react';
import MpesaForm from './MpesaForm';
import ScreenshotUpload from './ScreenshotUpload';
import PaymentConfirmation from './PaymentConfirmation';
import WhatsAppButton from '../whatsapp/WhatsAppButton';
import { useAuth } from '../../context/AuthContext';
import { useSettings } from '../../context/SettingsContext';
import { initiateSTKPush, initiateManualPayment, uploadScreenshot, submitPaymentConfirmation } from '../../services/paymentService';
import { formatKES } from '../../utils/formatters';
import { X, Copy, Check } from 'lucide-react';

const PaymentModal = ({ item, onClose, onSuccess }) => {
  const [method, setMethod] = useState('');
  const [loading, setLoading] = useState(false);
  const [transactionId, setTransactionId] = useState(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const [confirmationType, setConfirmationType] = useState('screenshot');
  const { user } = useAuth();
  const { settings, formatPaymentInstructions } = useSettings();

  const businessNumber = settings?.businessPhoneNumber || '0768784909';

  const handleSTKPush = async (phone) => {
    if (!settings?.enableSTKPush) {
      alert('STK Push is currently disabled. Please use manual payment.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const data = await initiateSTKPush(item._id, item.type, phone);
      setTransactionId(data.transactionId);
      setMethod('autogenerated');
    } catch (error) {
      console.error('STK Push error:', error);
      const msg = error.response?.data?.message || 'Payment failed. Please try again.';
      if (msg.includes('already own')) {
        alert('You already own this item. No payment needed.');
        onClose();
      } else {
        setError(msg);
        alert(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleManualPayment = async () => {
    if (!settings?.enableManualPayment) {
      alert('Manual payment is currently disabled. Please use STK Push.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      const data = await initiateManualPayment(item._id, item.type);
      setTransactionId(data.transactionId);
      setMethod('manual');
    } catch (error) {
      console.error('Manual payment error:', error);
      const msg = error.response?.data?.message || 'Failed to initiate manual payment';
      if (msg.includes('already own')) {
        alert('You already own this item. No payment needed.');
        onClose();
      } else {
        setError(msg);
        alert(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleScreenshotUpload = async (formData) => {
    setLoading(true);
    setError('');
    try {
      await uploadScreenshot(transactionId, formData);
      alert('✅ Screenshot uploaded! Awaiting verification.');
      if (onSuccess) onSuccess();
      setTimeout(() => onClose(), 2000);
    } catch (error) {
      console.error('Screenshot upload error:', error);
      const msg = error.response?.data?.message || 'Upload failed';
      setError(msg);
      alert(`❌ ${msg}`);
    } finally {
      setLoading(false);
    }
  };

  const handleMessageConfirmation = async (message) => {
    setLoading(true);
    setError('');
    try {
      await submitPaymentConfirmation(transactionId, message);
      alert('✅ Confirmation message received! Awaiting verification.');
      if (onSuccess) onSuccess();
      setTimeout(() => onClose(), 2000);
    } catch (error) {
      console.error('Confirmation error:', error);
      const msg = error.response?.data?.message || 'Submission failed';
      setError(msg);
      alert(`❌ ${msg}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-fade-in" onClick={onClose}>
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl max-w-md w-full max-h-[90vh] overflow-y-auto animate-slide-up" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="sticky top-0 bg-white dark:bg-gray-800 px-6 py-4 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center rounded-t-2xl">
          <h3 className="text-xl font-semibold text-gray-900 dark:text-white">Complete Payment</h3>
          <button onClick={onClose} className="p-1 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition">
            <X size={20} />
          </button>
        </div>

        <div className="p-6">
          {/* Item Details */}
          <div className="text-center mb-6 p-4 bg-gray-50 dark:bg-gray-700/50 rounded-xl">
            <h4 className="text-lg font-semibold text-gray-900 dark:text-white">{item.title}</h4>
            <p className="text-sm text-gray-500 dark:text-gray-400 capitalize mt-1">{item.type === 'software' ? '💻 Software' : '📄 Document'}</p>
            <div className="text-2xl font-bold text-primary-600 mt-2">{formatKES(item.price)}</div>
          </div>

          {error && (
            <div className="mb-4 p-3 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 rounded-lg text-center text-sm">
              ❌ {error}
            </div>
          )}

          {/* Payment Method Selection */}
          {!method && !transactionId && (
            <>
              <div className="flex flex-col sm:flex-row gap-4 mb-6">
                {settings?.enableSTKPush && (
                  <button
                    onClick={() => setMethod('autogenerated')}
                    disabled={loading}
                    className="flex-1 p-4 border-2 border-gray-200 dark:border-gray-700 rounded-xl hover:border-primary-500 hover:bg-primary-50 dark:hover:bg-primary-900/20 transition-all disabled:opacity-50"
                  >
                    <div className="text-3xl mb-2">📱</div>
                    <div className="font-semibold text-gray-900 dark:text-white">STK Push</div>
                    <div className="text-xs text-gray-500">Instant payment via M-Pesa</div>
                  </button>
                )}
                {settings?.enableManualPayment && (
                  <button
                    onClick={handleManualPayment}
                    disabled={loading}
                    className="flex-1 p-4 border-2 border-gray-200 dark:border-gray-700 rounded-xl hover:border-primary-500 hover:bg-primary-50 dark:hover:bg-primary-900/20 transition-all disabled:opacity-50"
                  >
                    <div className="text-3xl mb-2">💰</div>
                    <div className="font-semibold text-gray-900 dark:text-white">Send to Owner</div>
                    <div className="text-xs text-gray-500">Manual verification required</div>
                  </button>
                )}
              </div>
              {method === 'autogenerated' && <MpesaForm onSubmit={handleSTKPush} loading={loading} />}
            </>
          )}

          {/* STK Push Waiting Screen */}
          {method === 'autogenerated' && transactionId && (
            <div className="text-center py-4">
              <div className="text-5xl mb-4">📱</div>
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">STK Push Sent!</h3>
              <p className="text-gray-600 dark:text-gray-400 mb-4">Please check your phone and enter your M-Pesa PIN to complete the payment.</p>
              <div className="spinner mx-auto"></div>
              <p className="text-gray-400 text-sm mt-4 mb-6">Waiting for payment confirmation...</p>
              <WhatsAppButton message={`Hello, I'm trying to pay ${formatKES(item.price)} for ${item.title} via STK Push but not receiving the prompt.`} />
            </div>
          )}

          {/* Manual Payment Screen */}
          {method === 'manual' && transactionId && (
            <>
              <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg mb-6">
                <h4 className="font-semibold text-blue-800 dark:text-blue-300 mb-2">📋 Payment Instructions:</h4>
                <p className="text-gray-700 dark:text-gray-300 text-sm">{formatPaymentInstructions(settings?.paymentInstructions)}</p>
              </div>

              <div>
                <h4 className="text-lg font-semibold text-center mb-4">💵 Send Money to Owner</h4>

                {/* M-Pesa Details */}
                <div className="bg-gray-900 dark:bg-gray-950 rounded-xl p-5 text-center mb-6">
                  <div className="text-gray-400 text-xs mb-2">Send Money To:</div>
                  <div className="text-3xl font-mono font-bold text-white tracking-wider mb-2">{businessNumber}</div>
                  <div className="text-green-400 text-sm mb-3">Account: DocuSoft</div>
                  <div className="text-xl font-bold text-green-400 mb-4">{formatKES(item.price)}</div>
                  <button
                    onClick={() => copyToClipboard(businessNumber)}
                    className="inline-flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg transition"
                  >
                    {copied ? <Check size={16} /> : <Copy size={16} />}
                    {copied ? 'Copied!' : 'Copy Number'}
                  </button>
                </div>

                {/* Step-by-Step Guide */}
                <div className="bg-gray-50 dark:bg-gray-700/30 rounded-xl p-4 mb-6">
                  <h5 className="font-semibold mb-3">📱 How to Send Money via M-Pesa:</h5>
                  <ol className="space-y-2 text-sm text-gray-600 dark:text-gray-400 pl-5 list-decimal">
                    <li>Go to <strong>Safaricom M-Pesa</strong> on your phone</li>
                    <li>Select <strong>Send Money</strong></li>
                    <li>Enter Number: <strong>{businessNumber}</strong></li>
            
                    <li>Enter Amount: <strong>{formatKES(item.price)}</strong></li>
                    <li>Enter your M-Pesa PIN and confirm</li>
                    <li>Wait for confirmation SMS from M-Pesa</li>
                  </ol>
                </div>

                {/* Confirmation Type Toggle */}
                <div className="flex gap-2 border-b border-gray-200 dark:border-gray-700 mb-4">
                  <button
                    onClick={() => setConfirmationType('screenshot')}
                    className={`flex-1 py-2 text-sm font-medium transition ${
                      confirmationType === 'screenshot'
                        ? 'text-primary-600 border-b-2 border-primary-600'
                        : 'text-gray-500 hover:text-gray-700'
                    }`}
                  >
                    📸 Upload Screenshot
                  </button>
                  <button
                    onClick={() => setConfirmationType('message')}
                    className={`flex-1 py-2 text-sm font-medium transition ${
                      confirmationType === 'message'
                        ? 'text-primary-600 border-b-2 border-primary-600'
                        : 'text-gray-500 hover:text-gray-700'
                    }`}
                  >
                    ✍️ Paste Confirmation
                  </button>
                </div>

                {confirmationType === 'screenshot' && (
                  <ScreenshotUpload onUpload={handleScreenshotUpload} loading={loading} />
                )}

                {confirmationType === 'message' && (
                  <PaymentConfirmation onConfirm={handleMessageConfirmation} loading={loading} />
                )}

                {/* WhatsApp Support */}
                <div className="text-center mt-6">
                  <p className="text-sm text-gray-500 mb-2">After sending money, notify the owner:</p>
                  <WhatsAppButton message={`Hello, I just sent ${formatKES(item.price)} for ${item.title} via M-Pesa. Please verify. Transaction ID: ${transactionId}`} />
                </div>

                {/* Pending Info */}
                <div className="mt-4 p-3 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg text-center text-xs text-yellow-800 dark:text-yellow-400">
                  ⏳ Your payment will be verified by the admin within 24 hours.<br />
                  You will receive a confirmation once approved.
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default PaymentModal;